name: flutter_paystack_webview
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 0.0.1
homepage: https://github.com/laxusgooee/flutter_paystack_webview

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
   - assets/images/



environment:
  sdk: '>=3.4.3 <4.0.0'